# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4134c2163cd4acab49809daf5f3d5c330fe4072e438c6d6bb7e4b7315a8e77fe0004830532d4d16a6dfd6900f7e9fd9880ef1acbcb704bdd0ae9b14b69910ca0

test:
  secret_key_base: 75566b0507b82432986c2d0f7cbb05271dcd0814ba796665399ea369278f4544042d027a3ee0dcdad8e26c4976a35a1bbc0574562690899bf542b8d923d9f96e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
